//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FD.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> TransactionQnty { get; set; }
        public Nullable<double> TransactionPrice { get; set; }
        public Nullable<double> TransactionAmount { get; set; }
        public Nullable<bool> TransactionIsActive { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public Nullable<int> GuestId { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual User User { get; set; }
    }
}
